env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 12
rules: {
  'linebreak-style': 0,
  'indent': 0,
  'no-param-reassign': 0,
  'no-console': 0,
  'no-unreachable': 0,
  'no-alert': 0,
  'no-unused-vars': 0,
  'no-undef': 0,
  'no-restricted-syntax': 0,
  'class-methods-use-this': 0,
  'no-unused-expressions': 0,
  'no-array-constructor': 0,
  'no-await-in-loop': 0,
}
